---
title: Habits
author: Dahee Kim 
date: January 1, 2020
output:
  html_document:
    css: my_style.css
---
##Theme{.tabset .tabset-fade .tabset-pills}

###Basic Format
<div class="alert alert-info">
    title: Habits<br /> 
    author: Dahee Kim<br />
    date: January 1, 2020<br />
    output: html_document<br />
      &emsp;toc: TRUE #table of contents<br />
      &emsp;toc_deoth: 2 #hierarchy levels <br />
      &emsp;toc_float: TRUE #float the table contents to left<br />
      &emsp;number_section: TRUE #number of headers<br />
</div>

###Tabs
<div class="alert alert-info">
      ##Theme{.tabset .tabset-fade .tabset-pills}
      
      ###{Tab1}
      {contents}
      
      ###{Tab2}
      {contents}
</div>
###Theme
<p style="background-color: #cdc; border-radius: 5px;padding: 10px;border: 1px solid white">
    html_document:<br />
    &emsp;toc: TRUE #table of contents<br />
    &emsp;toc_deoth: 2 #hierarchy levels <br />
    &emsp;toc_float: TRUE #float the table contents to left<br />
    &emsp;number_section: TRUE #number of headers<br />
</p>
-**Default Theme**: `cerulean`, `cosmo`, `flatly`, `journal`, `lumen`, `paper`, `readable`, `sandstone`, `simplex`, `spacelab`, `united`, and `yeti`.<br />
-**highlight options**: `tango`, `pygments`, `kate`, `monochrome`, `espresso`, `zenburn`, `haddock`, `textmate`.

###**rmdformats** package

rmdformats package
[[Link]](https://cran.r-project.org/web/packages/rmdformats/rmdformats.pdf) 

<div class="emphasized">
  output: rmdformats::material
</div>


- `material`
- `readthedown`
- `html_clean`
- `html_docco`

###**prettydoc** package

prettydoc package <a href="https://cran.rstudio.com/web/packages/prettydoc/prettydoc.pdf">[Link]</a> 

<div class="emphasized">
    prettydoc::html_pretty<br />
    &emsp;theme: leonids<br />
    &emsp;highlight: github<br />
    &emsp;math: katex<br />
</div>

- The theme option: `cayman`, `tactile`, `architect`, `leonids`, and `hpstr`<br />
- The highlight option: `github`, or `vignette`.

