---
title: "Xlsx to csv"
author: "DaheeKim"
date: "2/2/2020"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
X044_OI_191024_Cohort_6_ <- read_excel("~/Downloads/attachments/044-OI-191024 (Cohort 6).xlsx")
```


```{r cars}
library(readxl)
files <- list.files(path = "~/Downloads/attachments", pattern = "*.xlsx", full.names = T)
files[1]
library(dplyr)
sheets <- excel_sheets(files[1])
sheets2 = sheets[[c("RTB1", "RTB2","RTB3","RTB4","RTB5")]]
sheets = sheets[which(sheets== "RTB1"|sheets== "RTB2"|sheets== "RTB3"|sheets== "RTB4"|sheets== "RTB5")]
str(sheets)
list_all_example <- lapply(sheets, function(x) read_excel(files[1], sheet = x, skip = 31))
str(list_all_example)
list<- lapply(list_all_example, function(x) write.csv(x,'x.csv' ))
write.csv(healthstudy,'healthstudy2.csv')
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
