library(readxl)
data<- read_excel("N:/DaheeKim/March/GrowthAnalysis/growthanalysis_final.xlsx",
                  sheet = "SAS")
attach(data)
names(data)
library(car)
qqPlot(data$OD)
qqPlot(data$BPR)
qqPlot(data$DO)
qqPlot(data$Mu)
qqPlot(data$MuMax)
qqPlot(data$DT)
qqPlot(data$Absor_675)
qqPlot(data$pH)
qqPlot(data$Absor_440)

c <- c("OD","BPR")
shapiro.test(OD)
shapiro.test(BPR)
shapiro.test(MuMax)
shapiro.test(Mu)
shapiro.test(DT)
shapiro.test(OD)
shapiro.test(OD)
shapiro.test(OD)
