---
title: "Design Experiment -- randomizr package"
author: Dahee Kim
date: January 4,2020
output: rmdformats::readthedown
---
*randomizr* is a package for experiment design and random sampling. 

```{r rows.print=8, pages.print=3}
library(formattable)
library(randomizr)
library(readxl)
data <- read_excel("~/Desktop/TankAssignment.xlsx",sheet = "Adjusted_Data")
head(data,30)    
```

#Complete Random Assignment
##Two-arm Designs
```{r}
Z <- complete_ra(N = 200)
table(Z)
Z <- complete_ra(N = 200, m = 50) #1 is 50
table(Z)
Z <- complete_ra(N = 1000, m_unit = rep(50, 1000)) #950 vs 50
table(Z)
Z <- complete_ra(N = 1000, prob = .111) #889 vs 111
table(Z)
Z <- complete_ra(N = 1000, prob_unit = rep(0.1, 1000)) #900 vs 100
table(Z)
Z <- complete_ra(N = 1000, conditions = c("control", "treatment")) #new label
table(Z)
```

##Multi-arm Designs
```{r}
Z <- complete_ra(N = 144, num_arms = 18)
table(Z)
Z <- complete_ra(N = 1000, m_each = c(300, 300, 400))
table(Z)
Z <- complete_ra(N = 1000, prob_each = c(.1, .2, .7))
table(Z)
Z <- complete_ra(N = 144, conditions = c("A","B","C","D","E","F","G","Ctrl_1", "Ctrl_2","H","K","L","P","Q","R","X","Y","Z"))
table(Z)
```

#Block Random Assignment
##Two-arm Designs
```{r}
blocks <- rep(c("A", "B","C"), times = c(50, 100, 200))
Z <- block_ra(blocks = blocks)
table(blocks, Z)

Z <- block_ra(blocks = blocks, prob = .3) #30% on 1, 70% on 0
table(blocks, Z)
Z <- block_ra(blocks = blocks, block_prob = c(.1, .2, .3)) #10%, 20%,30% on 1
table(blocks, Z)

Z <- block_ra(blocks = blocks, m = 20)#20 on 1, rest on 0
table(blocks, Z)
Z <- block_ra(blocks = blocks, block_m = c(20, 30, 40)) #20,30,40 on 1, rest on 0
table(blocks, Z)

Z <- block_ra(blocks = blocks,
              m_unit = rep(c(20, 30, 40),
              times = c(50, 100, 200))) #Assigned for 1
table(blocks, Z)

block_m_each <- rbind(c(10, 40),
                      c(30, 70),
                    c(50, 150)) #all assigned with label
Z <- block_ra(blocks = blocks, block_m_each = block_m_each,
conditions = c("control", "treatment"))
table(blocks, Z)
```

##Multi-arm Designs
```{r}
blocks <- rep(c("Left_Top", "Left_Bottom","Right_Top","Right_Bottom"), times = c(36,36,36,36))
Z <- block_ra(blocks = blocks, num_arms = 18,conditions = c("A","B","C","D","E","F","G","Ctrl_1", "Ctrl_2","H","K","L","P","Q","R","X","Y","Z"))
table(blocks, Z)
dt <- data.frame(blocks,Z)
formattable(head(dt),align="l")


# Multi-arm Designs with Different Ratio
blocks <- rep(c("A", "B","Control"), times = c(50, 100, 200))
block_m_each <- rbind(c(10, 20, 20),
                        c(30, 50, 20),
                        c(50, 75, 75))
Z <- block_ra(blocks = blocks, block_m_each = block_m_each,
conditions = c("control", "placebo", "treatment"))
table(blocks, Z)

Z <- block_ra(blocks = blocks, prob_each = c(.1, .1, .8)) #probabilty that each unit is assigned to each condition
table(blocks, Z)
```


