---
title: "Meta-Analysis"
output: html_notebook
---

quantitative and statistical approach for combining results of two or more previous research to arriave at conclusions about the body of research

| Advantage| Disadvantage |
|-|-|
| 1. Improved power and precision due to larger sample size | biases within study |
| 2. Quantify inconsistency in results between studies. | variation across studies |
| 3. Generalization of results | reporting biases |
| 4. Hypothesis testing can be applied on summary statistics |  |
| 5. Investigate presence of publication bias |  |


Process<br>

1) Formulate the problem using PICO model
    - Population (P) 
    - Intervention (I): intervention and control ex) Dose / Mode of delivery / frequency of delievery
      - What is the intervention and control Does the intervention have variations ?
      - Dose / Mode of delivery / frequency Which variations should be included? 
      - How will you handle studies where only handled.
      - How will trials that combine the interven interest be handled.
    - Comparisons (C) 
    - Outcomes (O)
      - Address outcomes that relate the beneficial effects as well as adverse effects
      - Define how the outcomes will be measured.
      - Limit primary outcomes to 2 - 3 which have impact on patient care
2) Literature search
    - Search Randomized trials: eliminate bias and confounding, may eliminate "publication bias"
    - Searching across multiple database
      - Bibliographic Databases: MEDLINE, EMBASE, CENTRA: fast and easy, various search methodology, indexing terms availble
      - Citation Indexes: SciSearch, SCOPUS
      - Dissertations and Theses can be searched in specific databases: ProQuest, Theses (UK), DissOnline (German).
      - Grey Literature: Conference abstracts
      - Full text search of journals in internet (not indexed) 
      - Conference abstracts: 50% of all trials reported dont reach full publication !! 
      - Trial registers : National (CTRI) and International
    - Develop a set of keywords
3) Study selection
    - Define selection criteria and have a form ex) unpublished studies included?  
    - Collect Study design data/ participants/ interventions/ outcome measures/ results
4) Decide the variables are allowed
  - Assessing Bias
    - Selection bias (Non randomized) 
    - Performance bias (Non blinded - patient & care givers)
    - Detection bias (Non blinded - assessor) 
    - Attrition bias
    - Reporting bias - may be one of the most im study.
      - Publication Bias: we can only find the results of published results
        - how to identify: funnel plot/ egger's regression test/begg's rank correlation test
          - funnel plot: effect size vs sample size(standard error). If LOWER LEFT is empty --> publication bias
          - Asymmetric funnel plot: precision vs Log odds ratio
        - solution: only larger studies/ file-drawer method / trim and fill method
          - file-drawer: large studies converge at the tip while smaller studies show symmetrical scatter at the base
      - Time lag bias: Results determine time taken to publish
      - Multiple publication bias: multiple publications from one trial
      - Location bias: english journals , strong significant effects/ which journal they are published to
      - Citation bias: Results determine citations
      - Outcome reporting bias : Selective reporting of only some outcomes
  - Effect(Difference between two groups) Size Measures
    - Dichotomous: Risk ratio, Risk Different, NNT, Odds Ratio
      - Risk: probability of getting the event
        - Risk ratio: Ratio of risk in the two groups
        - Risk difference: difference between risk in the two groups
      - Odds: ratio of the probability of getting the event to that not getting the event
        - Odss Ratio: ratio of odds of an event in the two groups
    - Continuous data: Mean Difference
      - Outcome scale is same: absolute difference betwen mean values of two groups
      - Outcome scale is not same: standardized mean differences / Hedges's g
    - Ordinal data : proportional odds ratio
    - Counts & rates of events data: Rate ratio
    - time to event data(survival) : Hazard ratio
  - Heterogeneity
    - Types
      - Clinical diversity : Arising due to participants / interventions / outcomes studied.
      - Methodological diversity: Arising due to variation in study methods
      - Statistical diversity: Arises due to clinical and methodological diversities.
    - How to test?
      - Cochrane's Q
      - I2 statistic: 25%(low heterogeneity), 50%(moderate), 75%(high)
5) Select the model
  - Data type
    - individual participant data: raw data
    - aggregate data: represents summary estimates such as odds ratios or relative risks
      - direct
      - indirect: effect of two treatments that were each compared against a similar control group
        - ex) A vs Control/ B vs Control --> A vs B
  - Directly synthesized studies
    - Fixed effects model:no heterogeneity. weighted average; usually inverse of the estimates variance; larger studies controbute more than smaller studies
      - assumption: ll studies investigate the same population, same variable and outcome definition
    - Random effects model: presence of heterogeneity. Weighted average of the effect sizes of ta group of studies
      - 1) inverse variance weighting
      - 2) un-weighting of 
    - Meta-regression: mixed of present and absence of heterogeneity
    
 | Fixed effects model | Random effects model |
|-|-|
| if heterogeneity is absent | if heterogeneity is presence |
| assumes size of treatment effect is the same(fixed)  across all studies | assumes size of treatment effect  varies across the studies |
| pooling: Mantel Haenszel or 1/variance | pooling: DSL method |     

  - Indirectly synthesized studies
    - Network meta-analysis: comparing three or more interventions simultaneously
    - Bayesian framework
    - Frequentist multivariate framework
    - Generalized pairwise modeeling framework
    - Tailored meta- analysis


How to prepare?

1) specify eligibility criteria
2) identifying, selecting and critically appraising studies
3) collecting appropriate data
4) what would be meaningful to analyze

What to include in report?

- Characteristics of included studies
  - Risk of bias table
- Data and analysis
- Figures : Study flow, forest plots, funnel plots, risk of bia
- Summary of findings
